### ISSUE TITLE
Review Sprint 1 - Backlog Refinement:

### ISSUE THREAD

**Issue by SharafElDinShamsElDin** [SharafElDinShamsElDin/sharafeldinshamseldin#1]
Sprint 1 - Backlog Refinement:
●	Task 1: Create user stories for Batch Branch Addition.
●	Task 2: Design the batch addition UI for Merchants.
●	Task 3: Integrate Google Places API for address search.
●	Task 4: Develop the database schema to store batch-added branches.

**Comment by TamannaSidd** [comment]
Search box should search for branch name?
